name: ci
on: push

jobs:
  docker:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Install yq for YAML parsing
        run: sudo apt-get update && sudo apt-get install -y jq && wget -O /tmp/yq https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 && chmod +x /tmp/yq && sudo mv /tmp/yq /usr/local/bin/
      -
        name: Checkout code
        uses: actions/checkout@v2
          
      -
        name: Print working directory
        run: pwd
      -
        name: List files in current directory
        run: ls -al
      -
        name: Extract image names from profile.yml
        id: extract-images
        run: |
            IMAGES=$(yq e '.images | keys | join(",")' profile.yml)
            echo "Extracted Images: $IMAGES"
            echo "::set-output name=images::$IMAGES"
      -
        name: Build and push images
        run: |
          IFS=',' read -ra IMGS <<< "${{ steps.extract-images.outputs.images }}"
          for i in "${IMGS[@]}"; do
            echo "Building image with tag: $i"
            docker build --build-arg IMG_TAG="$i" -t ghcr.io/portalhubyt/${{ github.event.repository.name }}:$i -f Dockerfile .
            docker push ghcr.io/portalhubyt/${{ github.event.repository.name }}:$i
          done
