name: run
on: push

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
  run:
    runs-on: ubuntu-latest
    needs: login
    container:
      image: ghcr.io/portalhubyt/template_server:latest
    steps:
      - run: |
          sh start.sh
